### ISSUE TITLE
How does one find the child ID?

### ISSUE THREAD

**Issue by Cerothen** [jcgoette/hi_mama_homeassistant#5]
I would like to use the integration you have created but I can't figure out the child ID

I tried 0 and 1 with no luck. If it's a UUID or something I'm not sure where to find it. Any advise would be great.

Thanks

**Comment by jcgoette** [comment]
I don't think you should really *need* the child ID, but it is exposed as an attribute of a child sensor.

**Comment by Cerothen** [comment]
The child ID is needed when adding the integration.
![Screenshot_20211231-174901_Home Assistant](https://user-images.githubusercontent.com/9008757/147840575-26f5545d-a9df-46a8-8958-bf63f210e35d.jpg)

**Comment by jcgoette** [comment]
Oh, I'm sorry. I was confusing this with another integration.

Fair warning, I don't think this integration is currently working properly.

You get the child ID by going to https://www.himama.com/accounts and getting the last part of the URL for the child listed there.

**Comment by Cerothen** [comment]
Thanks for getting back to me, I did some light tinkering and can confirm that the integration currently seems to have some issues.
